import {test,expect,type Page} from '@playwright/test';
import fs from 'node:fs/promises';
import path from 'node:path';
import {seedCandidate,inspectFixture,conflictFixture,requireIsolatedQuarantineWorkspace} from './quarantine-fixture';
const headers={'X-Local-Resume':'1'},root=path.resolve(import.meta.dirname,'../..');
const ids=Array.from({length:102},(_,i)=>`11111111-1111-4111-8111-${String(i).padStart(12,'0')}`);
function report(bytes=1024){return {checkedAt:'2026-10-01T00:00:00Z',graceDays:30,referencesVerified:true,bytesComplete:true,kinds:[{key:'image',count:102,bytes:102*bytes},{key:'pdf',count:0,bytes:0},{key:'other',count:0,bytes:0}],statuses:[{key:'in_use',count:0,bytes:0},{key:'recent',count:0,bytes:0},{key:'candidate',count:101,bytes:101*bytes},{key:'check',count:1,bytes}],items:ids.map((id,i)=>({kind:'image',id,status:i===0?'check':'candidate',reason:i===0?'file_mismatch':'unreferenced_image',bytes,lastModified:'2026-08-01T00:00:00Z'})),digest:'a'.repeat(64)};}
async function open(page:Page){await page.goto('/');await page.getByRole('button',{name:'备份与恢复',exact:true}).click();const d=page.getByRole('dialog',{name:'备份与恢复',exact:true});await d.getByRole('tab',{name:'空间检查',exact:true}).click();return d;}
test.beforeEach(()=>{test.skip(process.env.RESUME_TEST_ISOLATED!=='1','Disposable workspace required');requireIsolatedQuarantineWorkspace();});

// Catches noncandidate selection, selection loss on pagination, POST before confirmation,
// new operation/digest/items on uncertain retry and treating attention HTTP 200 as success.
test('candidate selection survives pages and uncertain acknowledgement retries the exact request',async({page})=>{
 const bodies:any[]=[];let posted=false;
 await page.route('**/api/storage/preview',r=>r.fulfill({json:report()}));
 await page.route('**/api/storage/quarantine?page=*',r=>r.fulfill({json:{items:[],page:0,hasMore:false,unreadable:1}}));
 await page.route('**/api/storage/quarantine',async r=>{bodies.push(r.request().postDataJSON());posted=true;if(bodies.length===1)await r.abort();else await r.fulfill({json:{id:bodies[0].operationId,state:'attention',createdAt:'2026-10-01T00:00:00Z',updatedAt:'2026-10-01T00:00:00Z',items:bodies[0].items.map((i:any)=>({...i,bytes:1024})),bytes:2048,backupId:null,digest:'b'.repeat(64),errorCode:'QUARANTINE_IO_FAILED'}});});
 const d=await open(page);await expect(d.getByTestId('storage-item-'+ids[0]).getByRole('checkbox')).toHaveCount(0);
 await expect(d.getByTestId('storage-item-'+ids[1]).getByRole('checkbox')).toBeVisible();await d.getByTestId('storage-item-'+ids[1]).getByRole('checkbox').check();await d.getByRole('group',{name:'空间清单分页'}).getByRole('button',{name:'下一页'}).click();await d.getByTestId('storage-item-'+ids[20]).getByRole('checkbox').check();await expect(d.getByTestId('quarantine-selection')).toContainText('2 项');
 await d.getByRole('button',{name:'查看暂存清单'}).click();await expect(d.getByRole('button',{name:'确认暂存选中项'})).toBeDisabled();expect(posted).toBe(false);await d.getByLabel('确认暂存这些未使用文件').scrollIntoViewIfNeeded();await fs.mkdir(path.join(root,'output'),{recursive:true});await page.screenshot({path:path.join(root,'output/quarantine-confirmation.png'),animations:'disabled'});
 await d.getByLabel('确认暂存这些未使用文件').check();await d.getByRole('button',{name:'确认暂存选中项'}).click();await expect(d.getByRole('alert').filter({hasText:'NETWORK_ERROR'})).toBeVisible();await expect(d.getByTestId('storage-item-'+ids[20]).getByRole('checkbox')).toBeDisabled();await expect(d.getByRole('button',{name:'重新检查空间'})).toBeDisabled();
 await expect(d.getByRole('button',{name:'关闭备份与恢复'})).toBeDisabled();await page.keyboard.press('Escape');await expect(d).toBeVisible();await d.getByRole('button',{name:'用同一清单重试暂存'}).click();await expect(d.getByRole('alert').filter({hasText:'QUARANTINE_IO_FAILED'})).toBeVisible();await expect(d.getByText('已暂存选中项', {exact:false})).toHaveCount(0);expect(bodies).toHaveLength(2);expect(bodies[1]).toEqual(bodies[0]);expect(bodies[0].items).toEqual([{kind:'image',id:ids[1]},{kind:'image',id:ids[20]}]);expect(bodies[0].previewDigest).toBe('a'.repeat(64));
 await expect(d.getByText(/摘要无法读取/)).toBeVisible();
});

test('preparing HTTP 200 is a recoverable reservation, not successful movement',async({page})=>{
 let current:any;let scans=0;
 await page.route('**/api/storage/preview',r=>{scans++;return r.fulfill({json:report()});});await page.route('**/api/storage/quarantine?page=*',r=>r.fulfill({json:{items:current?[current]:[],page:0,hasMore:false,unreadable:0}}));
 await page.route('**/api/storage/quarantine',r=>{const body=r.request().postDataJSON();current={id:body.operationId,state:'preparing',createdAt:'2026-10-01T00:00:00Z',updatedAt:'2026-10-01T00:00:00Z',items:[{kind:'image',id:ids[1],bytes:1024}],bytes:1024,backupId:null,digest:'c'.repeat(64),errorCode:'BACKUP_FAILED'};return r.fulfill({json:current});});
 const d=await open(page);await d.getByTestId('storage-item-'+ids[1]).getByRole('checkbox').check();await d.getByRole('button',{name:'查看暂存清单'}).click();await d.getByLabel('确认暂存这些未使用文件').check();await d.getByRole('button',{name:'确认暂存选中项'}).click();await expect(d.getByRole('alert').filter({hasText:'暂存尚未完成'})).toContainText('准备中');await expect(d.getByRole('status').filter({hasText:'已暂存选中项'})).toHaveCount(0);await expect(d.getByTestId('quarantine-'+current.id)).toContainText('BACKUP_FAILED');await expect(d.getByTestId('quarantine-'+current.id).getByRole('button',{name:'查看恢复清单'})).toBeEnabled();expect(scans).toBeGreaterThan(1);
});

test('unreadable acknowledgement retains the exact pending request',async({page})=>{
 const bodies:any[]=[];await page.route('**/api/storage/preview',r=>r.fulfill({json:report()}));await page.route('**/api/storage/quarantine?page=*',r=>r.fulfill({json:{items:[],page:0,hasMore:false,unreadable:0}}));await page.route('**/api/storage/quarantine',r=>{const body=r.request().postDataJSON();bodies.push(body);return bodies.length===1?r.fulfill({body:'{"id":',contentType:'application/json'}):r.fulfill({json:{id:body.operationId,state:'quarantined',createdAt:'2026-10-01T00:00:00Z',updatedAt:'2026-10-01T00:00:00Z',items:body.items.map((i:any)=>({...i,bytes:1024})),bytes:1024,backupId:null,digest:'c'.repeat(64),errorCode:null}});});
 const d=await open(page);await d.getByTestId('storage-item-'+ids[1]).getByRole('checkbox').check();await d.getByRole('button',{name:'查看暂存清单'}).click();await d.getByLabel('确认暂存这些未使用文件').check();await d.getByRole('button',{name:'确认暂存选中项'}).click();await expect(d.getByRole('alert').filter({hasText:'NETWORK_ERROR'})).toBeVisible();await expect(d.getByTestId('storage-item-'+ids[1]).getByRole('checkbox')).toBeDisabled();await d.getByRole('button',{name:'用同一清单重试暂存'}).click();await expect(d.getByRole('status').filter({hasText:'已暂存选中项'})).toBeVisible();expect(bodies[1]).toEqual(bodies[0]);
});

const malformedAcknowledgements=[
 {name:'empty object',status:200,make:(_receipt:any)=>({})},
 {name:'null',status:200,make:(_receipt:any)=>null},
 {name:'partial receipt',status:200,make:(receipt:any)=>({...receipt,items:undefined})},
 {name:'mismatched operation',status:200,make:(receipt:any)=>({...receipt,id:ids[3]})},
 {name:'non-success empty object',status:503,make:(_receipt:any)=>({})},
 {name:'non-success null',status:503,make:(_receipt:any)=>null},
 {name:'non-success invalid field types',status:503,make:(_receipt:any)=>({code:12,message:'broken'})}
];
for(const action of ['quarantine','restore'] as const)for(const malformed of malformedAcknowledgements){
 test(`${action} parseable ${malformed.name} acknowledgement preserves renderable locked review and exact retry`,async({page})=>{
  const bodies:any[]=[],urls:string[]=[],pageErrors:string[]=[];let completed=false;
  const receipt={id:ids[0],state:'quarantined',createdAt:'2026-10-01T00:00:00Z',updatedAt:'2026-10-01T00:00:00Z',items:[{kind:'image',id:ids[1],bytes:1024}],bytes:1024,backupId:null,digest:'b'.repeat(64),errorCode:null};
  page.on('pageerror',error=>pageErrors.push(error.message));
  await page.route('**/api/storage/preview',r=>r.fulfill({json:report()}));
  await page.route('**/api/storage/quarantine?page=*',r=>r.fulfill({json:{items:action==='restore'?[{...receipt,state:completed?'restored':'quarantined'}]:[],page:0,hasMore:false,unreadable:0}}));
  await page.route(action==='restore'?'**/api/storage/quarantine/*/restore':'**/api/storage/quarantine',r=>{
   const body=r.request().postDataJSON();bodies.push(body);urls.push(r.request().url());completed=true;
   const valid={...receipt,id:action==='restore'?receipt.id:body.operationId,state:action==='restore'?'restored':'quarantined'};
   return r.fulfill({status:bodies.length===1?malformed.status:200,contentType:'application/json',body:JSON.stringify(bodies.length===1?malformed.make(valid):valid)});
  });
  const d=await open(page);
  if(action==='restore'){await d.getByRole('button',{name:'查看恢复清单'}).click();await d.getByLabel('确认恢复这些暂存文件').check();await d.getByRole('button',{name:'确认恢复原位置'}).click();}
  else{await d.getByTestId('storage-item-'+ids[1]).getByRole('checkbox').check();await d.getByRole('button',{name:'查看暂存清单'}).click();await d.getByLabel('确认暂存这些未使用文件').check();await d.getByRole('button',{name:'确认暂存选中项'}).click();}
  await expect(d.getByRole('alert').filter({hasText:'NETWORK_ERROR'})).toBeVisible();await expect(d.getByRole('button',{name:'关闭备份与恢复'})).toBeDisabled();for(let i=0;i<4;i++)await expect(d.getByRole('tab').nth(i)).toBeDisabled();
  const confirmation=d.getByLabel(action==='restore'?'确认恢复这些暂存文件':'确认暂存这些未使用文件');await expect(confirmation).toBeChecked();await expect(confirmation).toBeDisabled();
  const review=d.locator(action==='restore'?'[aria-label="暂存恢复确认"]':'[aria-label="暂存确认"]');await expect(review).toContainText(ids[1]);await expect(review).toContainText('1 项');await page.keyboard.press('Escape');await expect(d).toBeVisible();
  if(action==='quarantine'){await expect(d.getByTestId('storage-item-'+ids[1]).getByRole('checkbox')).toBeChecked();await expect(d.getByTestId('storage-item-'+ids[1]).getByRole('checkbox')).toBeDisabled();await expect(d.getByRole('button',{name:'重新检查空间'})).toBeDisabled();}
  await d.getByRole('button',{name:action==='restore'?'用同一请求重试恢复':'用同一清单重试暂存'}).click();await expect(d.getByRole('status').filter({hasText:action==='restore'?'已恢复原位置':'已暂存选中项'})).toBeVisible();expect(bodies).toHaveLength(2);expect(bodies[1]).toEqual(bodies[0]);expect(urls[1]).toBe(urls[0]);expect(pageErrors).toEqual([]);
  if(action==='restore')expect(bodies[0]).toEqual({expectedDigest:'b'.repeat(64),confirm:true});else{expect(bodies[0].operationId).toMatch(/^[0-9a-f-]{36}$/);expect(bodies[0].previewDigest).toBe('a'.repeat(64));expect(bodies[0].items).toEqual([{kind:'image',id:ids[1]}]);}
 });
}

for(const action of ['quarantine','restore'] as const)test(`${action} valid known error refreshes evidence and unlocks parent`,async({page})=>{
 let scans=0,historyReads=0;const errors:string[]=[];
 const receipt={id:ids[0],state:'quarantined',createdAt:'2026-10-01T00:00:00Z',updatedAt:'2026-10-01T00:00:00Z',items:[{kind:'image',id:ids[1],bytes:1024}],bytes:1024,backupId:null,digest:'b'.repeat(64),errorCode:null};
 page.on('pageerror',error=>errors.push(error.message));await page.route('**/api/storage/preview',r=>{scans++;return r.fulfill({json:report()});});await page.route('**/api/storage/quarantine?page=*',r=>{historyReads++;return r.fulfill({json:{items:action==='restore'?[receipt]:[],page:0,hasMore:false,unreadable:0}});});
 await page.route(action==='restore'?'**/api/storage/quarantine/*/restore':'**/api/storage/quarantine',r=>r.fulfill({status:409,json:{code:action==='restore'?'QUARANTINE_CONFLICT':'STORAGE_PREVIEW_CHANGED',message:'合成已确认失败，文件保留。'}}));
 const d=await open(page);await expect(d.getByRole('button',{name:'关闭备份与恢复'})).toBeEnabled();const originalScans=scans,originalHistory=historyReads;
 if(action==='restore'){await d.getByRole('button',{name:'查看恢复清单'}).click();await d.getByLabel('确认恢复这些暂存文件').check();await d.getByRole('button',{name:'确认恢复原位置'}).click();}
 else{await d.getByTestId('storage-item-'+ids[1]).getByRole('checkbox').check();await d.getByRole('button',{name:'查看暂存清单'}).click();await d.getByLabel('确认暂存这些未使用文件').check();await d.getByRole('button',{name:'确认暂存选中项'}).click();}
 await expect(d.getByRole('alert').filter({hasText:action==='restore'?'QUARANTINE_CONFLICT':'STORAGE_PREVIEW_CHANGED'})).toBeVisible();await expect(d.getByRole('button',{name:'关闭备份与恢复'})).toBeEnabled();await expect(d.getByRole('tab',{name:'备份与恢复',exact:true})).toBeEnabled();expect(scans).toBeGreaterThan(originalScans);expect(historyReads).toBeGreaterThan(originalHistory);expect(errors).toEqual([]);
 if(action==='restore'){await expect(d.getByLabel('确认恢复这些暂存文件')).toBeChecked();await expect(d.getByRole('button',{name:'确认恢复原位置'})).toBeEnabled();}
 else{await expect(d.locator('[aria-label="暂存确认"]')).toHaveCount(0);await expect(d.getByTestId('quarantine-selection')).toContainText('已选 0 项');await expect(d.getByTestId('storage-item-'+ids[1]).getByRole('checkbox')).toBeEnabled();}
});

test('page selection respects 100 item and one GiB caps',async({page})=>{
 await page.route('**/api/storage/preview',r=>r.fulfill({json:report(600*1048576)}));await page.route('**/api/storage/quarantine?page=*',r=>r.fulfill({json:{items:[],page:0,hasMore:false,unreadable:0}}));
 const d=await open(page);await d.getByTestId('storage-item-'+ids[1]).getByRole('checkbox').check();await expect(d.getByTestId('storage-item-'+ids[2]).getByRole('checkbox')).toBeDisabled();await expect(d.getByRole('button',{name:'选择本页候选'})).toBeDisabled();
 await page.unroute('**/api/storage/preview');await page.route('**/api/storage/preview',r=>r.fulfill({json:report()}));await d.getByRole('button',{name:'重新检查空间'}).click();for(let i=0;i<5;i++){await d.getByRole('button',{name:'选择本页候选'}).click();await d.getByRole('group',{name:'空间清单分页'}).getByRole('button',{name:'下一页'}).click();}await d.getByTestId('storage-item-'+ids[100]).getByRole('checkbox').check();await expect(d.getByTestId('quarantine-selection')).toContainText('100 项');await expect(d.getByTestId('storage-item-'+ids[101]).getByRole('checkbox')).toBeDisabled();
});

test('held inventory and active anomalies sharing IDs remain visible and unselectable',async({page})=>{
 const fixture=report();fixture.items=[{kind:'image',id:ids[0],status:'check',reason:'missing_image',bytes:0,lastModified:'2026-08-01T00:00:00Z'},{kind:'image',id:ids[0],status:'quarantined',reason:'quarantined_file',bytes:1024,lastModified:'2026-10-01T00:00:00Z'},{kind:'image',id:ids[1],status:'check',reason:'incomplete_quarantine',bytes:512,lastModified:'2026-10-01T00:00:00Z'}];fixture.statuses=[{key:'in_use',count:0,bytes:0},{key:'recent',count:0,bytes:0},{key:'candidate',count:0,bytes:0},{key:'check',count:2,bytes:512},{key:'quarantined',count:1,bytes:1024}];fixture.kinds=[{key:'image',count:3,bytes:1536},{key:'pdf',count:0,bytes:0},{key:'other',count:0,bytes:0}];
 await page.route('**/api/storage/preview',r=>r.fulfill({json:fixture}));await page.route('**/api/storage/quarantine?page=*',r=>r.fulfill({json:{items:[],page:0,hasMore:false,unreadable:0}}));const d=await open(page);await expect(d.getByTestId('storage-item-'+ids[1])).toContainText('暂存记录不完整');await d.getByLabel('空间检查文件范围').selectOption('all');await expect(d.getByTestId('storage-item-'+ids[0])).toHaveCount(2);await expect(d.locator('.storage-items').getByRole('checkbox')).toHaveCount(0);await d.getByLabel('空间检查文件范围').selectOption('quarantined');await expect(d.getByTestId('storage-item-'+ids[0])).toContainText('仍占磁盘空间');await expect(d.getByTestId('storage-summary-quarantined')).toContainText('已暂存');
});

test('history confirms recovery, retains conflicts and retries stable token; dark narrow keyboard',async({page})=>{
 const receipt={id:ids[0],state:'preparing',createdAt:'2026-10-01T00:00:00Z',updatedAt:'2026-10-01T00:00:00Z',items:[{kind:'image',id:ids[1],bytes:1024}],bytes:1024,backupId:ids[2],digest:'b'.repeat(64),errorCode:'BACKUP_FAILED'};let calls=0;const bodies:any[]=[];const pages:number[]=[];
 await page.route('**/api/storage/preview',r=>r.fulfill({json:report()}));await page.route('**/api/storage/quarantine?page=*',r=>{const p=Number(new URL(r.request().url()).searchParams.get('page'));pages.push(p);return r.fulfill({json:{items:p?[]:[{...receipt,state:calls>=2?'restored':receipt.state,errorCode:calls>=2?null:receipt.errorCode}],page:p,hasMore:p===0,unreadable:0}});});
 await page.route('**/api/storage/quarantine/*/restore',async r=>{calls++;bodies.push(r.request().postDataJSON());if(calls===1)await r.fulfill({status:409,json:{code:'QUARANTINE_CONFLICT',message:'原位置存在文件，未覆盖。'}});else if(calls===2)await r.abort();else await r.fulfill({json:{...receipt,state:'restored',errorCode:null}});});
 const d=await open(page);await expect(d.getByTestId('quarantine-'+ids[0])).toContainText('准备中');await expect(d.getByRole('link',{name:'下载移前完整备份'})).toHaveAttribute('href',`/api/backups/${ids[2]}/download`);await d.getByRole('group',{name:'暂存记录分页'}).getByRole('button',{name:'下一页'}).click();await d.getByRole('group',{name:'暂存记录分页'}).getByRole('button',{name:'上一页'}).click();expect(pages).toContain(1);
 await d.getByRole('button',{name:'查看恢复清单'}).click();await expect(d.getByRole('button',{name:'确认恢复原位置'})).toBeDisabled();expect(calls).toBe(0);await d.getByLabel('确认恢复这些暂存文件').check();await d.getByRole('button',{name:'确认恢复原位置'}).click();await expect(d.getByRole('alert').filter({hasText:'QUARANTINE_CONFLICT'})).toBeVisible();await expect(d.getByLabel('确认恢复这些暂存文件')).toBeChecked();await d.getByRole('button',{name:'确认恢复原位置'}).click();await expect(d.getByRole('alert').filter({hasText:'NETWORK_ERROR'})).toBeVisible();await d.getByRole('button',{name:'用同一请求重试恢复'}).click();await expect(d.getByRole('status').filter({hasText:'已恢复原位置'})).toBeVisible();expect(bodies).toEqual(Array(3).fill({expectedDigest:'b'.repeat(64),confirm:true}));
 await expect(d.getByRole('button',{name:'关闭备份与恢复'})).toBeEnabled();await page.keyboard.press('Escape');await page.getByLabel('界面风格').selectOption('b');await page.getByRole('switch',{name:'深色模式'}).click();await page.setViewportSize({width:390,height:1000});await page.getByRole('button',{name:'备份与恢复',exact:true}).click();await d.getByRole('tab',{name:'空间检查',exact:true}).click();await expect(d.getByTestId('quarantine-'+ids[0])).toContainText('已恢复');expect(await d.evaluate(el=>el.scrollWidth<=el.clientWidth+1)).toBe(true);await d.locator('.quarantine-history').scrollIntoViewIfNeeded();await fs.mkdir(path.join(root,'output'),{recursive:true});await page.screenshot({path:path.join(root,'output/quarantine-dark-mobile.png'),animations:'disabled'});await d.getByRole('button',{name:'关闭备份与恢复'}).focus();await page.keyboard.press('Shift+Tab');await expect(d.getByRole('button',{name:'关闭',exact:true})).toBeFocused();await page.keyboard.press('Escape');await expect(page.getByRole('button',{name:'备份与恢复',exact:true})).toBeFocused();
});

test('recovery keeps parent controls locked until the resulting storage scan finishes',async({page})=>{
 const receipt={id:ids[0],state:'quarantined',createdAt:'2026-10-01T00:00:00Z',updatedAt:'2026-10-01T00:00:00Z',items:[{kind:'image',id:ids[1],bytes:1024}],bytes:1024,backupId:null,digest:'b'.repeat(64),errorCode:null};let restored=false,release!:()=>void,started!:()=>void;const scanStarted=new Promise<void>(resolve=>started=resolve),held=new Promise<void>(resolve=>release=resolve);
 await page.route('**/api/storage/preview',async r=>{if(restored){started();await held;}await r.fulfill({json:report()});});await page.route('**/api/storage/quarantine?page=*',r=>r.fulfill({json:{items:[{...receipt,state:restored?'restored':'quarantined'}],page:0,hasMore:false,unreadable:0}}));await page.route('**/api/storage/quarantine/*/restore',r=>{restored=true;return r.fulfill({json:{...receipt,state:'restored'}});});
 const d=await open(page);await d.getByRole('button',{name:'查看恢复清单'}).click();await d.getByLabel('确认恢复这些暂存文件').check();await d.getByRole('button',{name:'确认恢复原位置'}).click();await scanStarted;try{await expect(d.getByRole('button',{name:'关闭备份与恢复'})).toBeDisabled();await expect(d.getByRole('button',{name:/重新检查空间|正在检查/})).toBeDisabled();}finally{release();}await expect(d.getByRole('button',{name:'关闭备份与恢复'})).toBeEnabled();
});

test('real old uncataloged image moves after backup, survives lost acknowledgement and restores exact bytes',async({page,request})=>{
 const previous=await fs.readFile(path.join(root,'output/quarantine-persistence.json'),'utf8').then(JSON.parse).catch(()=>undefined);if(previous?.container===process.env.RESUME_TEST_APP_CONTAINER){expect(previous.operationId).toMatch(/^[0-9a-f]{8}(?:-[0-9a-f]{4}){3}-[0-9a-f]{12}$/);expect(previous.recoveryToken).toMatch(/^[a-f0-9]{64}$/);const response=await request.post(`/api/storage/quarantine/${previous.operationId}/restore`,{headers,data:{expectedDigest:previous.recoveryToken,confirm:true}});expect(response.ok()).toBeTruthy();expect((await response.json()).state).toBe('restored');}
 const upload=await request.post('/api/assets',{headers,multipart:{file:{name:'quarantine-synthetic.png',mimeType:'image/png',buffer:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+/l9sAAAAASUVORK5CYII=','base64')}}});expect(upload.ok()).toBeTruthy();const candidate=seedCandidate((await upload.json()).id),before=inspectFixture(candidate.id);const receipts:any[]=[];
 await page.route('**/api/storage/quarantine',async route=>{const response=await route.fetch();receipts.push(await response.json());if(receipts.length===1)await route.abort();else await route.fulfill({response});});
 const d=await open(page),item=d.getByTestId('storage-item-'+candidate.id);await expect(item).toContainText('清理候选');await item.getByRole('checkbox').check();await d.getByRole('button',{name:'查看暂存清单'}).click();await d.getByLabel('确认暂存这些未使用文件').check();await d.getByRole('button',{name:'确认暂存选中项'}).click();await expect(d.getByRole('alert').filter({hasText:'NETWORK_ERROR'})).toBeVisible();await d.getByRole('button',{name:'用同一清单重试暂存'}).click();await expect(d.getByRole('status').filter({hasText:'已暂存选中项'})).toBeVisible();expect(receipts[1]).toEqual(receipts[0]);const receipt=receipts[0];expect(receipt.state).toBe('quarantined');expect(receipt.backupId).toBeTruthy();const zip=await request.get(`/api/backups/${receipt.backupId}/download`);expect(zip.ok()).toBeTruthy();expect((await zip.body()).subarray(0,2).toString()).toBe('PK');expect(inspectFixture(candidate.id,receipt.id).files).toEqual(before.files);expect(inspectFixture(candidate.id).exists).toBe(false);
 const held=d.getByTestId('quarantine-'+receipt.id);await held.getByRole('button',{name:'查看恢复清单'}).click();await d.getByLabel('确认恢复这些暂存文件').check();conflictFixture(candidate.id,'create');await d.getByRole('button',{name:'确认恢复原位置'}).click();await expect(d.getByRole('alert').filter({hasText:'QUARANTINE_CONFLICT'})).toBeVisible();expect(inspectFixture(candidate.id,receipt.id).files).toEqual(before.files);conflictFixture(candidate.id,'remove');await d.getByRole('button',{name:'确认恢复原位置'}).click();await expect(d.getByRole('status').filter({hasText:'已恢复原位置'})).toBeVisible();expect(inspectFixture(candidate.id).files).toEqual(before.files);const fresh=await(await request.get('/api/storage/preview')).json();expect(fresh.items.find((i:any)=>i.id===candidate.id).status).toBe('recent');
 const heldFixture=seedCandidate((await upload.json()).id),fingerprint=inspectFixture(heldFixture.id);const preview=await(await request.get('/api/storage/preview')).json();const operationId=crypto.randomUUID();const heldResponse=await request.post('/api/storage/quarantine',{headers,data:{operationId,previewDigest:preview.digest,items:[{kind:'image',id:heldFixture.id}],confirm:true}});expect(heldResponse.ok()).toBeTruthy();const heldReceipt=await heldResponse.json();expect(heldReceipt.state).toBe('quarantined');await fs.mkdir(path.join(root,'output'),{recursive:true});await fs.writeFile(path.join(root,'output/quarantine-persistence.json'),JSON.stringify({operationId,recoveryToken:heldReceipt.digest,imageId:heldFixture.id,normalizedSHA:fingerprint.sha,files:fingerprint.files,container:process.env.RESUME_TEST_APP_CONTAINER},null,2));
});
