<script setup lang="ts">
import {computed,onMounted,reactive,ref} from 'vue';
import {api} from './api';
import {modelSettings,type ModelProfile,type ModelSettings} from './modelApi';
const state=ref<ModelSettings>(),busy=ref(false),error=ref(''),notice=ref(''),editing=ref<string|null|undefined>();
const form=reactive({name:'',provider:'dashscope',baseUrl:'',model:'',apiKey:'',clearKey:false});
const tests=reactive<Record<string,string>>({});
const savedKey=computed(()=>state.value?.profiles.find(profile=>profile.id===editing.value)?.hasApiKey);
const providerName=(id:string)=>state.value?.presets.find(preset=>preset.id===id)?.name||id;
async function action(run:()=>Promise<void>){if(busy.value)return;busy.value=true;error.value='';notice.value='';try{await run();}catch(cause){error.value=cause instanceof Error?cause.message:String(cause);}finally{busy.value=false;}}
async function load(){state.value=await modelSettings();}
function preset(){const value=state.value?.presets.find(item=>item.id===form.provider);if(value){form.baseUrl=value.baseUrl;form.model=value.model;form.apiKey='';form.clearKey=false;}}
function edit(profile?:ModelProfile){editing.value=profile?.id||null;Object.assign(form,{name:profile?.name||'',provider:profile?.provider||'dashscope',baseUrl:profile?.baseUrl||'',model:profile?.model||'',apiKey:'',clearKey:false});if(!profile)preset();}
function cancel(){form.apiKey='';editing.value=undefined;}
async function save(){if(!state.value)return;state.value=await api<ModelSettings>(editing.value?`/api/models/profiles/${editing.value}`:'/api/models/profiles',{...form,expectedRevision:state.value.revision},editing.value?'PUT':'POST');cancel();notice.value='模型配置已保存。';}
async function select(profile:ModelProfile){if(!state.value)return;state.value=await api(`/api/models/profiles/${profile.id}/default`,{expectedRevision:state.value.revision});notice.value='已设为默认文字模型。';}
async function remove(profile:ModelProfile){if(!state.value||!window.confirm(`删除模型配置「${profile.name}」？`))return;state.value=await api(`/api/models/profiles/${profile.id}`,{expectedRevision:state.value.revision},'DELETE');notice.value='模型配置已删除。';}
async function enable(event:Event){const previous=state.value;if(!previous)return;const enabled=(event.target as HTMLInputElement).checked;try{state.value=await api('/api/models/enabled',{expectedRevision:previous.revision,enabled},'PUT');}catch(cause){(event.target as HTMLInputElement).checked=previous.enabled;throw cause;}}
async function test(profile:ModelProfile){if(!state.value)return;tests[profile.id]='正在测试…';try{const result=await api<{connected:boolean;elapsedMs:number}>(`/api/models/profiles/${profile.id}/test`,{expectedRevision:state.value.revision});tests[profile.id]=`连接成功 · ${result.elapsedMs} ms`;}catch(cause){tests[profile.id]='测试失败';throw cause;}}
onMounted(()=>action(load));
</script>
<template>
 <main class="model-page"><header class="model-page-heading"><div><span class="rw-overline">个人配置</span><h1>模型设置</h1><p>管理用于文字润色的模型，选择一个作为默认。</p></div><button class="rw-primary" :disabled="busy||!state?.readable" @click="edit()">＋ 添加模型</button></header>
  <div class="model-page-toolbar"><label><input type="checkbox" :checked="state?.enabled||false" :disabled="busy||!state?.readable" aria-label="启用文字润色" @change="event=>action(()=>enable(event))">启用文字润色</label><span>只有点击润色并确认发送后，才调用模型。</span><button :disabled="busy" @click="action(load)">刷新</button></div>
  <p v-if="state&&!state.readable" class="model-error" role="alert">模型设置无法读取，请保留原文件并检查本机数据目录。</p><p v-if="error" class="model-error" role="alert">{{error}}</p><p v-if="notice" class="model-notice" role="status">{{notice}}</p>
  <form v-if="editing!==undefined" class="model-edit" aria-label="编辑模型配置" @submit.prevent="action(save)"><div class="model-edit-heading"><h2>{{editing?'编辑模型':'添加模型'}}</h2><button type="button" :disabled="busy" @click="cancel">取消</button></div><fieldset :disabled="busy"><div class="model-fields"><label class="form-label">配置名称<input v-model="form.name" required maxlength="50" aria-label="模型配置名称" placeholder="例如：DashScope 求职润色"></label><label class="form-label">服务商<select v-model="form.provider" aria-label="模型服务商" @change="preset"><option v-for="preset in state?.presets" :key="preset.id" :value="preset.id">{{preset.name}}</option></select></label><label class="form-label model-wide">Base URL<input v-model="form.baseUrl" required maxlength="300" type="url" aria-label="模型 Base URL"></label><label class="form-label">文字模型<input v-model="form.model" required maxlength="80" aria-label="文字模型名称" placeholder="填写服务商提供的模型名称"></label><label class="form-label">API Key<input v-model="form.apiKey" type="password" maxlength="512" autocomplete="new-password" aria-label="模型 API Key" :placeholder="savedKey?'已配置；留空保留原密钥':'输入 API Key'"></label></div><label v-if="savedKey" class="model-clear-key"><input v-model="form.clearKey" type="checkbox" aria-label="清除已保存的 API Key">清除已保存的 API Key</label><p class="model-key-note">密钥保存在本机服务端，列表不回显明文，不进入简历备份。</p><button type="submit" class="rw-primary">保存模型配置</button></fieldset></form>
  <p v-if="state?.readable&&!state.profiles.length&&editing===undefined" class="model-empty">尚未配置模型。添加服务商和模型后，可以测试连接并设置默认模型。</p>
  <section v-if="state" class="model-grid" aria-label="已配置的模型"><article v-for="profile in state.profiles" :key="profile.id" class="model-card" :data-testid="'model-'+profile.id"><div class="model-card-heading"><div><h2>{{profile.name}}</h2><p>{{providerName(profile.provider)}}</p></div><span v-if="state.defaultId===profile.id" class="model-default">默认文字模型</span></div><dl><div><dt>Base URL</dt><dd :title="profile.baseUrl">{{profile.baseUrl}}</dd></div><div><dt>文字模型</dt><dd>{{profile.model}}</dd></div><div><dt>API Key</dt><dd>{{profile.hasApiKey?'已配置 · ••••••••':'未配置'}}</dd></div></dl><p v-if="tests[profile.id]" class="model-test-result" role="status">{{tests[profile.id]}}</p><footer><button :disabled="busy" @click="edit(profile)">编辑</button><button :disabled="busy||!profile.hasApiKey" @click="action(()=>test(profile))">测试连接</button><button :disabled="busy||state.defaultId===profile.id" @click="action(()=>select(profile))">设为文字默认</button><button class="quiet-danger" :disabled="busy" @click="action(()=>remove(profile))">删除</button></footer></article></section>
  <p class="model-footer-note">“测试连接”会向所选服务发送固定的 OK 测试文字，可能产生少量调用费用。不会发送简历内容。</p>
 </main>
</template>
