"""Build deterministic, synthetic PDF resumes for local import verification."""
import argparse
import io
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont
from reportlab.lib.pagesizes import A4
from reportlab.lib.utils import ImageReader
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.pdfgen.canvas import Canvas
from reportlab.lib.pdfencrypt import StandardEncryption

ROOT = Path(__file__).resolve().parents[1]
FONT_PATH = ROOT / 'src/main/resources/static/fonts/LocalResumeSans-Regular.ttf'
FONT_NAME = 'SyntheticResumeSans'
pdfmetrics.registerFont(TTFont(FONT_NAME, str(FONT_PATH)))


def _page(canvas, second=False):
    width, height = A4
    canvas.setFont(FONT_NAME, 21)
    canvas.drawString(55, height - 75, '奶龙')
    canvas.setFont(FONT_NAME, 11)
    canvas.drawString(55, height - 104, '求职方向：Java 后端实习')
    if second:
        canvas.drawString(55, height - 158, '项目经历')
        canvas.drawString(55, height - 181, '本地简历工作台：实现可核验的 PDF 文字提取和人工校对。')
        canvas.drawString(55, height - 204, '未归类内容：第二页的原文也应保留。')
    else:
        canvas.drawString(55, height - 128, '邮箱：nailong@example.invalid')
        canvas.drawString(55, height - 151, '电话：13800000000')
        canvas.drawString(55, height - 174, '城市：杭州')
        canvas.drawString(55, height - 218, '教育背景')
        canvas.drawString(55, height - 241, '示例理工大学 · 软件工程 · 2023–2027')
        canvas.drawString(55, height - 286, '专业技能')
        canvas.drawString(55, height - 309, 'Java、PostgreSQL、Git、Docker')
        canvas.drawString(55, height - 354, '项目经历')
        canvas.drawString(55, height - 377, '本地简历工作台：使用 Spring Boot 处理本地文件与 PDF 导出。')


def _scan_image():
    image = Image.new('RGB', (800, 1040), '#ffffff')
    draw = ImageDraw.Draw(image)
    font = ImageFont.truetype(str(FONT_PATH), 42)
    draw.text((58, 70), '奶龙 · 扫描样本', font=font, fill='#253746')
    draw.text((58, 175), '这页只有像素，没有可选择的文字。', font=font, fill='#253746')
    for y in (270, 315, 405, 450):
        draw.rectangle((58, y, 680, y + 9), fill='#d1dae1')
    stream = io.BytesIO()
    image.save(stream, format='PNG')
    return stream.getvalue()


def fixture_bytes(kind):
    if kind not in {'text', 'two-pages', 'scanned', 'encrypted'}:
        raise ValueError(f'Unknown synthetic PDF kind: {kind}')
    output = io.BytesIO()
    encryption = StandardEncryption(userPassword='test-only', ownerPassword='owner-only', strength=128) if kind == 'encrypted' else None
    canvas = Canvas(output, pagesize=A4, pageCompression=1, invariant=1, encrypt=encryption)
    canvas.setTitle('Resume Workbench synthetic PDF import fixture')
    canvas.setAuthor('Resume Workbench QA')
    if kind == 'scanned':
        width, height = A4
        canvas.drawImage(ImageReader(io.BytesIO(_scan_image())), 28, 28, width=width - 56, height=height - 56)
    else:
        _page(canvas)
        if kind == 'two-pages':
            canvas.showPage()
            _page(canvas, second=True)
    canvas.showPage()
    canvas.save()
    return output.getvalue()


def semantic_content(payload):
    # Compressed stream bytes can differ across OS zlib builds; the visible and
    # extractable content is the portable fixture contract.
    from pypdf import PdfReader
    reader = PdfReader(io.BytesIO(payload))
    encrypted = reader.is_encrypted
    if encrypted and not reader.decrypt('test-only'):
        raise ValueError('Synthetic encrypted PDF password differs')
    return encrypted, tuple((tuple(map(float, page.mediabox)), page.extract_text(),
                             '/XObject' in page['/Resources']) for page in reader.pages)


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--output-dir', type=Path, default=ROOT / 'fixtures/pdf')
    parser.add_argument('--check', action='store_true', help='Compare generated bytes with checked-in fixtures without writing')
    args = parser.parse_args()
    args.output_dir.mkdir(parents=True, exist_ok=True)
    for kind in ('text', 'two-pages', 'scanned', 'encrypted'):
        destination = args.output_dir / f'{kind}.pdf'
        payload = fixture_bytes(kind)
        if args.check:
            if not destination.is_file() or semantic_content(destination.read_bytes()) != semantic_content(payload):
                raise SystemExit(f'Synthetic PDF fixture differs: {kind}')
        else:
            destination.write_bytes(payload)
    print('Four synthetic PDF fixtures verified.' if args.check else 'Generated four synthetic PDF fixtures.')
